// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoEhqJAuNXavTPGxXoppv0S0QTrtNayEI',
    appId: '1:42446955304:web:05ca65ca2ca76752e9261d',
    messagingSenderId: '42446955304',
    projectId: 'fazzaapp-5d93c',
    authDomain: 'fazzaapp-5d93c.firebaseapp.com',
    storageBucket: 'fazzaapp-5d93c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiKrvMKDx4rcunDtrnQn9ash1afTgAHAU',
    appId: '1:42446955304:android:95bdc2f2144de447e9261d',
    messagingSenderId: '42446955304',
    projectId: 'fazzaapp-5d93c',
    storageBucket: 'fazzaapp-5d93c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhGBDURks_W6O0blqlixeJvzeVVLgtWJ0',
    appId: '1:42446955304:ios:8d38a46288f4cfc3e9261d',
    messagingSenderId: '42446955304',
    projectId: 'fazzaapp-5d93c',
    storageBucket: 'fazzaapp-5d93c.firebasestorage.app',
    iosBundleId: 'com.example.untitled8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhGBDURks_W6O0blqlixeJvzeVVLgtWJ0',
    appId: '1:42446955304:ios:8d38a46288f4cfc3e9261d',
    messagingSenderId: '42446955304',
    projectId: 'fazzaapp-5d93c',
    storageBucket: 'fazzaapp-5d93c.firebasestorage.app',
    iosBundleId: 'com.example.untitled8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoEhqJAuNXavTPGxXoppv0S0QTrtNayEI',
    appId: '1:42446955304:web:9a467c46072d9d85e9261d',
    messagingSenderId: '42446955304',
    projectId: 'fazzaapp-5d93c',
    authDomain: 'fazzaapp-5d93c.firebaseapp.com',
    storageBucket: 'fazzaapp-5d93c.firebasestorage.app',
  );
}
